version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: ragalaxy-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ragalaxy --save 60 1000 --loglevel warning --maxmemory 512mb --maxmemory-policy allkeys-lru
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: ragalaxy